### PR TITLE
Fix README.md a little.

### PR DESCRIPTION
**Pull request by Yomi0**
Fix README.md a little.

### CODE REVIEW

**Comment by Yomi0** [comment]
I also wanted to fix line 38, but I can't figure out what its trying to convey.

**Comment by marcelhollerbach** [comment]
Hi, at first thx for the  help :) 

This sentences wants to explain what happens wants once a file "appears".

appears means here: It is found while iterating throuw the directory where it is located, or it was created while monitoring the directory.

fetching stat is not really done there anymore ... have to update it.

The mimetype of a file is something like the kind of file, all files with the same mimetype are having the same icon. Looking for this mimetype takes some time. this is why it is done asynchorne. In other words: this is done in a seperated thread.

Is it a bit more understandable ? :)

**Comment by Yomi0** [comment]
'Once a file appears, big operations such as fetching stat's, mimetype and the like are done asynchronously. ' ?

**Comment by marcelhollerbach** [comment]
I am ok with that :) you can leave the stat´s away.

**Comment by Yomi0** [comment]
> I am ok with that :) you can leave the stat´s away.

You want me to remove the 'fetching stat's' part?

**Comment by marcelhollerbach** [comment]
yep

**Comment by Yomi0** [comment]
Right, okay.

**Comment by marcelhollerbach** [comment]
Okay, looks cool! :) ready for merge ?

**Comment by Yomi0** [comment]
Yep.

**Pull request merged**
